output "name" {
  value       = local.name
  description = "This will hold the final name that will be generated by the label modules"
}

output "tags" {
  value       = local.combined_tags
  description = "This will hold the final tags that will be generated by the label modules"
}

output "context" {
  value = local.output_context
}
